# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM nouchka/sqlite3:latest

# Copy the local package files to the container's workspace.
WORKDIR /root

EXPOSE 8088

COPY server/sqlite-database.db ./