version: "3.8"
services:
  db:
    restart: always
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "54321:5432"
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=172.18.0.1 
      - DATABASE_USER=postgres 
      - DATABASE_PASSWORD=123456 
      - DATABASE_NAME=postgres 
      - DATABASE_PORT=54321
    depends_on:
      - db