version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "8088"
    volumes:
      - sqlite_db:/root
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - SQLITEPATH=/root/sqlite-database.db
    volumes_from: 
      - db
    depends_on:
      - db
volumes:
  sqlite_db:
    external: false